name: digifood_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  go_router: ^10.1.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1
  very_good_analysis: ^5.0.0+1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
